// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: common/code.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	// 未知状态
	Code_UNKNOWN Code = 0
	// 成功
	Code_SUCCESS Code = 1
	// 错误的过期时间
	Code_ILLEGAL_EXPIRE_TIME Code = 2
	// 过期时间早于当前时间
	Code_EXPIRE_TIME_EARLIER_THAN_NOW Code = 3
	// 已重试次数超过最大
	Code_RETRY_MAX_TIMES Code = 4
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "ILLEGAL_EXPIRE_TIME",
		3: "EXPIRE_TIME_EARLIER_THAN_NOW",
		4: "RETRY_MAX_TIMES",
	}
	Code_value = map[string]int32{
		"UNKNOWN":                      0,
		"SUCCESS":                      1,
		"ILLEGAL_EXPIRE_TIME":          2,
		"EXPIRE_TIME_EARLIER_THAN_NOW": 3,
		"RETRY_MAX_TIMES":              4,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_common_code_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_common_code_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_common_code_proto_rawDescGZIP(), []int{0}
}

var File_common_code_proto protoreflect.FileDescriptor

var file_common_code_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x70, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x17, 0x0a,
	0x13, 0x49, 0x4c, 0x4c, 0x45, 0x47, 0x41, 0x4c, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x5f,
	0x54, 0x49, 0x4d, 0x45, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45,
	0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x45, 0x41, 0x52, 0x4c, 0x49, 0x45, 0x52, 0x5f, 0x54, 0x48,
	0x41, 0x4e, 0x5f, 0x4e, 0x4f, 0x57, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x54, 0x52,
	0x59, 0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x10, 0x04, 0x42, 0x08, 0x5a,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_code_proto_rawDescOnce sync.Once
	file_common_code_proto_rawDescData = file_common_code_proto_rawDesc
)

func file_common_code_proto_rawDescGZIP() []byte {
	file_common_code_proto_rawDescOnce.Do(func() {
		file_common_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_code_proto_rawDescData)
	})
	return file_common_code_proto_rawDescData
}

var file_common_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_code_proto_goTypes = []interface{}{
	(Code)(0), // 0: common.Code
}
var file_common_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_code_proto_init() }
func file_common_code_proto_init() {
	if File_common_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_code_proto_goTypes,
		DependencyIndexes: file_common_code_proto_depIdxs,
		EnumInfos:         file_common_code_proto_enumTypes,
	}.Build()
	File_common_code_proto = out.File
	file_common_code_proto_rawDesc = nil
	file_common_code_proto_goTypes = nil
	file_common_code_proto_depIdxs = nil
}
