// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/expire.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _expire_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Expire with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Expire) Validate() error {
	if m == nil {
		return nil
	}

	switch m.Expire.(type) {

	case *Expire_ExpireAt:

		if v, ok := interface{}(m.GetExpireAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExpireValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Expire_ExpireDuration:

		if v, ok := interface{}(m.GetExpireDuration()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExpireValidationError{
					field:  "ExpireDuration",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ExpireValidationError is the validation error returned by Expire.Validate if
// the designated constraints aren't met.
type ExpireValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExpireValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExpireValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExpireValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExpireValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExpireValidationError) ErrorName() string { return "ExpireValidationError" }

// Error satisfies the builtin error interface
func (e ExpireValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExpire.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExpireValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExpireValidationError{}
