// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/target.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _target_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Target with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Target) Validate() error {
	if m == nil {
		return nil
	}

	switch m.Target.(type) {

	case *Target_GrpcTarget:

		if v, ok := interface{}(m.GetGrpcTarget()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TargetValidationError{
					field:  "GrpcTarget",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Target_HttpTarget:

		if v, ok := interface{}(m.GetHttpTarget()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TargetValidationError{
					field:  "HttpTarget",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// TargetValidationError is the validation error returned by Target.Validate if
// the designated constraints aren't met.
type TargetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TargetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TargetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TargetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TargetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TargetValidationError) ErrorName() string { return "TargetValidationError" }

// Error satisfies the builtin error interface
func (e TargetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTarget.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TargetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TargetValidationError{}

// Validate checks the field values on GrpcTarget with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *GrpcTarget) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GrpcUrl

	return nil
}

// GrpcTargetValidationError is the validation error returned by
// GrpcTarget.Validate if the designated constraints aren't met.
type GrpcTargetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrpcTargetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrpcTargetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrpcTargetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrpcTargetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrpcTargetValidationError) ErrorName() string { return "GrpcTargetValidationError" }

// Error satisfies the builtin error interface
func (e GrpcTargetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrpcTarget.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrpcTargetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrpcTargetValidationError{}

// Validate checks the field values on HttpTarget with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *HttpTarget) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for HttpUrl

	return nil
}

// HttpTargetValidationError is the validation error returned by
// HttpTarget.Validate if the designated constraints aren't met.
type HttpTargetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpTargetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpTargetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpTargetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpTargetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpTargetValidationError) ErrorName() string { return "HttpTargetValidationError" }

// Error satisfies the builtin error interface
func (e HttpTargetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpTarget.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpTargetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpTargetValidationError{}
