// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: common/target.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// target 目标
	//
	// Types that are assignable to Target:
	//	*Target_GrpcTarget
	//	*Target_HttpTarget
	Target isTarget_Target `protobuf_oneof:"target"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_target_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_common_target_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_common_target_proto_rawDescGZIP(), []int{0}
}

func (m *Target) GetTarget() isTarget_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (x *Target) GetGrpcTarget() *GrpcTarget {
	if x, ok := x.GetTarget().(*Target_GrpcTarget); ok {
		return x.GrpcTarget
	}
	return nil
}

func (x *Target) GetHttpTarget() *HttpTarget {
	if x, ok := x.GetTarget().(*Target_HttpTarget); ok {
		return x.HttpTarget
	}
	return nil
}

type isTarget_Target interface {
	isTarget_Target()
}

type Target_GrpcTarget struct {
	// grpc_target grpc远程目标
	GrpcTarget *GrpcTarget `protobuf:"bytes,11,opt,name=grpc_target,json=grpcTarget,proto3,oneof"`
}

type Target_HttpTarget struct {
	// http_target http远程目标
	HttpTarget *HttpTarget `protobuf:"bytes,12,opt,name=http_target,json=httpTarget,proto3,oneof"`
}

func (*Target_GrpcTarget) isTarget_Target() {}

func (*Target_HttpTarget) isTarget_Target() {}

type GrpcTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// grpc_url 任务触发时调用的远程地址，必须是grpc格式
	GrpcUrl string `protobuf:"bytes,2,opt,name=grpc_url,json=grpcUrl,proto3" json:"grpc_url,omitempty"`
}

func (x *GrpcTarget) Reset() {
	*x = GrpcTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_target_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTarget) ProtoMessage() {}

func (x *GrpcTarget) ProtoReflect() protoreflect.Message {
	mi := &file_common_target_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTarget.ProtoReflect.Descriptor instead.
func (*GrpcTarget) Descriptor() ([]byte, []int) {
	return file_common_target_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcTarget) GetGrpcUrl() string {
	if x != nil {
		return x.GrpcUrl
	}
	return ""
}

type HttpTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// http_url 任务触发时调用的远程地址，必须是http格式
	HttpUrl string `protobuf:"bytes,2,opt,name=http_url,json=httpUrl,proto3" json:"http_url,omitempty"`
}

func (x *HttpTarget) Reset() {
	*x = HttpTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_target_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpTarget) ProtoMessage() {}

func (x *HttpTarget) ProtoReflect() protoreflect.Message {
	mi := &file_common_target_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpTarget.ProtoReflect.Descriptor instead.
func (*HttpTarget) Descriptor() ([]byte, []int) {
	return file_common_target_proto_rawDescGZIP(), []int{2}
}

func (x *HttpTarget) GetHttpUrl() string {
	if x != nil {
		return x.HttpUrl
	}
	return ""
}

var File_common_target_proto protoreflect.FileDescriptor

var file_common_target_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x80, 0x01,
	0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x35, 0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x74,
	0x74, 0x70, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x68, 0x74, 0x74, 0x70,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x22, 0x27, 0x0a, 0x0a, 0x47, 0x72, 0x70, 0x63, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x72, 0x70, 0x63, 0x55, 0x72, 0x6c, 0x22, 0x27, 0x0a, 0x0a, 0x48, 0x74, 0x74,
	0x70, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x74, 0x74, 0x70, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x74, 0x74, 0x70, 0x55,
	0x72, 0x6c, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x6a, 0x6f, 0x63, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x72,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_target_proto_rawDescOnce sync.Once
	file_common_target_proto_rawDescData = file_common_target_proto_rawDesc
)

func file_common_target_proto_rawDescGZIP() []byte {
	file_common_target_proto_rawDescOnce.Do(func() {
		file_common_target_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_target_proto_rawDescData)
	})
	return file_common_target_proto_rawDescData
}

var file_common_target_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_target_proto_goTypes = []interface{}{
	(*Target)(nil),     // 0: common.Target
	(*GrpcTarget)(nil), // 1: common.GrpcTarget
	(*HttpTarget)(nil), // 2: common.HttpTarget
}
var file_common_target_proto_depIdxs = []int32{
	1, // 0: common.Target.grpc_target:type_name -> common.GrpcTarget
	2, // 1: common.Target.http_target:type_name -> common.HttpTarget
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_target_proto_init() }
func file_common_target_proto_init() {
	if File_common_target_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_target_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_target_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_target_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_target_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Target_GrpcTarget)(nil),
		(*Target_HttpTarget)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_target_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_target_proto_goTypes,
		DependencyIndexes: file_common_target_proto_depIdxs,
		MessageInfos:      file_common_target_proto_msgTypes,
	}.Build()
	File_common_target_proto = out.File
	file_common_target_proto_rawDesc = nil
	file_common_target_proto_goTypes = nil
	file_common_target_proto_depIdxs = nil
}
